AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create ECR repositories for Lambda functions'

Parameters:
  Region:
    Type: String
    Default: us-east-1
    Description: AWS region for ECR repositories

Resources:
  LambdaFunction1Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-1-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction2Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-2-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction3Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-3-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction4Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-4-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction5Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-5-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction6Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-6-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction7Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-7-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction8Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-8-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction9Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-9-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

  LambdaFunction10Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-function-10-repo
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE

Outputs:
  RepositoryURLs:
    Description: URLs of all ECR repositories
    Value: !Join
      - ', '
      - - !GetAtt LambdaFunction1Repo.RepositoryUri
        - !GetAtt LambdaFunction2Repo.RepositoryUri
        - !GetAtt LambdaFunction3Repo.RepositoryUri
        - !GetAtt LambdaFunction4Repo.RepositoryUri
        - !GetAtt LambdaFunction5Repo.RepositoryUri
        - !GetAtt LambdaFunction6Repo.RepositoryUri
        - !GetAtt LambdaFunction7Repo.RepositoryUri
        - !GetAtt LambdaFunction8Repo.RepositoryUri
        - !GetAtt LambdaFunction9Repo.RepositoryUri
        - !GetAtt LambdaFunction10Repo.RepositoryUri

